data_ingestion_config:
    dataset_download_file_name: Airline_satisfaction.csv
    dataset_download_id: https://raw.githubusercontent.com/ARPITA-ds/AIRLINE/master/cleaned_airline1.csv
    ingested_dir: ingested_data
    ingested_test_file: test.csv
    ingested_train_file: train.csv
    ingested_dir: stage00_data_ingestion
    raw_data_dir: raw_data

training_pipeline_config:
    artifact_dir : artifact
    pipeline_name : Airline


data_transformation_config:
    data_transformation_dir: stage02_data_transformation
    preprocessing_object_dir: preprocessing
    preprocessing_object_file_name: preprocessing_obj.pkl
    data_transformed_dir: transformed_data
    transformed_train_dir_key: train_csv
    transformed_test_dir_key: test_csv


model_trainer_config:
  model_reports_dir: model_eval_reports
  model_trainer_dir: stage04_model_training
